export const projectTypes=[
    "Personal Project",
    "Hackathon",
    "Research Paper",
    "College Competition",
    "Internship",
]

export const projectDomains=[
    "Front-End Web Development",
    "Full Stack Development",
    "Android App development",
    "IOS App development",
    "Hybrid App development",
    "Web + App Devlopment",
    "Game Development",
    "ML/AI",
    "Data Science",
    "Internet of Things(Iot)",
    "AR/VR/MR",
    "Block Chain",
]

export const frameWorks=[
    { frameWork: 'ARCore' },
    { frameWork: 'ASP.NET' },
    { frameWork: 'Angular JS' },
    { frameWork: 'Apache Spark' },
    { frameWork: 'Arduino' },
    { frameWork: 'Azure ML Studio' },
    { frameWork: 'Blender' },
    { frameWork: 'Django' },
    { frameWork: 'Eris Industries' },
    { frameWork: 'Ethereum' },
    { frameWork: 'Express JS' },
    { frameWork: 'Firebase ML Kit' },
    { frameWork: 'Flask' },
    { frameWork: 'Flutter' },
    { frameWork: 'Google Cloud ML Engine' },
    { frameWork: 'Ionic' },
    { frameWork: 'Keras' },
    { frameWork: 'Laravel' },
    { frameWork: 'Matplotlib' },
    { frameWork: 'Maya' },
    { frameWork: 'Microsoft Cognitve Toolkit' },
    { frameWork: 'MixedReality Toolkit' },
    { frameWork: 'Mobile Angular UI' },
    { frameWork: 'Multichain' },
    { frameWork: 'Native Script' },
    { frameWork: 'Node JS' },
    { frameWork: 'Numpy' },
    { frameWork: 'OpenCV' },
    { frameWork: 'Openblockchain' },
    { frameWork: 'Other' },
    { frameWork: 'Pandas' },
    { frameWork: 'Pytorch' },
    { frameWork: 'R3 Corda' },
    { frameWork: 'React JS' },
    { frameWork: 'React Native' },
    { frameWork: 'React VR' },
    { frameWork: 'Ruby on Rails' },
    { frameWork: 'Scikit-Learn' },
    { frameWork: 'SketchUp' },
    { frameWork: 'Spring' },
    { frameWork: 'Tensorflow' },
    { frameWork: 'Unity3D' },
    { frameWork: 'Unreal Engine' },
    { frameWork: 'Vue JS' },
    { frameWork: 'Vuforia' },
    { frameWork: 'Wikitude' },
    { frameWork: 'Xamarin' },
    { frameWork: 'iOS ARKit' },
    { frameWork: 'jQuery' }
  ]



export const programmingLanguages=[
    {language:"C"},
    {language:"C#"},
    {language:"C++"},
    {language:"CSS"},
    {language:"Curl"},
    {language:"Dart"},
    {language:"HTML"},
    {language:"Java"},
    {language:"Javascript"},
    {language:"Kotlin"},
    {language:"MATLAB"},
    {language:"Mongo DB"},
    {language:"No SQL"},
    {language:"Perl"},
    {language:"PHP"},
    {language:"Python"},
    {language:"Ruby"},
    {language:"Rust"},
    {language:"MySQL"},
    {language:"Swift"},
    {language:"TypeScript"},
    {language:"XML"},
    {language:"GoLang"},
]

export const departments=[
    { department: 'Aerospace' },
    { department: 'Automobile' },
    { department: 'Bioinformatics' },
    { department: 'Biomedical' },
    { department: 'Biotechnology' },
    { department: 'Chemical' },
    { department: 'Civil' },
    { department: 'Computer Science' },
    { department: 'Electrical and Electronics' },
    { department: 'Electronics & Communication' },
    { department: 'Genetic' },
    { department: 'Information Technology' },
    { department: 'Mechanical' },
    { department: 'Mechatronics' },
    { department: 'Nanotechnology' },
    { department: 'Nuclear' },
    { department: 'Software' }
  ]